### ISSUE TITLE
Order the channels in the overall channel listing

### ISSUE THREAD

**Issue by flotwig** [flotwig/StatsBot#12]

**Comment by sebastianbarfurth** [comment]
The ability to filter the channels would make sense to be able to search for the desired channel. The [list.js project](https://github.com/javve/list.js) is simple and doesn't have dependencies. It's very easy to integrate, so it seems to be worth considering. Though writing a custom solution is very easy as well, it just seems like reinventing the wheel.

**Comment by flotwig** [comment]
Nice, even better. I'll use that.

P.S. Long time no see! :wave:

**Comment by flotwig** [comment]
Alright, completely redid the chanstats landing page. Now it's auto-sorted and searchable with list.js. https://chanstats.snoonet.org/
