### ISSUE TITLE
Fix throttling

### ISSUE THREAD

**Issue by flotwig** [flotwig/StatsBot#4]
cinch seems to be throttling throughput. If the bot is opered, it should be able to send/recv as fast as physically possible

**Comment by sebastianbarfurth** [comment]
Doesn't seem like an issue with the code (apart from maybe sending an oper command).

**Comment by flotwig** [comment]
Agreed. There's no way to fix this in cinch besides just hardcoding 9999999 events/s like I've already done, so closing for now.
