### ISSUE TITLE
how to make the stats page

### ISSUE THREAD

**Issue by Conver** [flotwig/StatsBot#6]
I got the bot running on my IRC and it generates the log files, but how do I get it to generate the stats page? The stats folder is empty.

I see in the code that it needs some kind of template file, where do I find that one?

Thanks

**Comment by flotwig** [comment]
pisg generates the stats, pisg should run on a cronjob using the pisg.cfg generated by StatsBot when a channel is added/removed. 

indexTemplate.html is only needed if you want to generate an index.html with a list of the channels with stats in it.

**Comment by Conver** [comment]
Can you give me an example about the cronjob?

**Comment by flotwig** [comment]
Look at the documentation for pisg, it's an integral part of this script.
